name: sealed_writer
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_writer
homepage: https://github.com/6thsolution/dart_sealed

version: 1.13.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1

# remove this on pub branch
publish_to: 'none'
